### ISSUE TITLE
can't concat str to bytes

### ISSUE THREAD

**Issue by stephenhoos** [amsehili/genRSS#9]
I am running the program directly as listed in the instructions, and I only get the error "can't concat str to bytes."  I this for Python 2?

**Comment by amsehili** [comment]
Hello,
Could you share the whole exception message please?
Thanks!

**Comment by KAMiKAZOW** [comment]
Yes, this is for Python2. Someone made a port to Python3: https://github.com/cpmpercussion/genRSS/tree/python3

The only change required to actually work is replacing ["xrange" with "range" in line 436](https://github.com/cpmpercussion/genRSS/blob/python3/genRSS.py#L436). I've created a Pull Request over there to address that: https://github.com/cpmpercussion/genRSS/pull/1

That fork also uses Mutagen to extract ID3Tags from files. It doesn't work with the fake test files because of that but with actual MP3s it works fine.

Wouldn't mind if @amsehili incorporated that fork's branch and my PR in this upstream project.

One downside if that Python3 port that still needs to be addressed are a few hardcoded values: https://github.com/cpmpercussion/genRSS/commit/19d9d832b400300a5e72c8f3e897e43eb465c5c6

Those are currently not extracted from "Artist", "Album", etc. elements and sadly that's above my skill level.

**Comment by stephenhoos** [comment]
I must have had a problem with my computer.  I am trying it on a different system, and it is working fine.
